# Generated by Django 5.1.1 on 2024-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0005_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='AGE',
            field=models.PositiveIntegerField(),
        ),
    ]
