# Generated by Django 5.1.1 on 2024-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0006_alter_registrationform_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='CATEGORY',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='GENDER',
            field=models.CharField(max_length=20),
        ),
    ]
