# Generated by Django 5.1.1 on 2024-09-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0007_alter_registrationform_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='USER_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
