# Generated by Django 5.1.1 on 2024-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0009_remove_booking_category_remove_booking_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='USER_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='USER_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='USER_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
