# Generated by Django 5.1.1 on 2024-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0011_booking_category_alter_booking_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='TOKEN',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
