# Generated by Django 5.1.1 on 2024-09-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0012_booking_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='PASSWORD',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='PASSWORD',
        ),
    ]
