# Generated by Django 5.1.1 on 2024-09-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0015_alter_booking_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='TOKEN',
            new_name='Token',
        ),
    ]
